In [1]:
# Importing NumPy library

import numpy as np

In [2]:
# Create a NumPy array

arr = np.array([10, 20, 30, 40, 50])

print("Original Array:", arr)

Original Array: [10 20 30 40 50]


In [3]:
# Calculate Mean, Max, Min, and Sum

print("Mean:", np.mean(arr))
print("Max:", np.max(arr))
print("Min:", np.min(arr))
print("Sum:", np.sum(arr))

Mean: 30.0
Max: 50
Min: 10
Sum: 150


In [4]:
# Create two arrays

arr_1 = np.array([1, 2, 3])
arr_2 = np.array([4, 5, 6])

print("Array 1:", arr_1)
print("Array 2:", arr_2)

Array 1: [1 2 3]
Array 2: [4 5 6]


In [5]:
# Addition and Multiplication

addition_result = arr_1 + arr_2
multiplication_result = arr_1 * arr_2

print("Addition Result:", addition_result)
print("Multiplication Result:", multiplication_result)

Addition Result: [5 7 9]
Multiplication Result: [ 4 10 18]


In [6]:
# Create a 3x3 Matrix

matrix_3x3 = np.arange(1, 10).reshape(3, 3)

print("3x3 Matrix:")
print(matrix_3x3)

3x3 Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
